[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[options]
verbose = 3
debug = 0
runuser = asterisk
rungroup = asterisk
maxcalls = 50
maxload = 0.9
languageprefix = yes
documentation_language = fr_FR
hideconnect = yes
lockconfdir = no
stdexten = gosub
live_dangerously = no
