[general]
dateformat=%F %T.%3q
exec_after_rotate=gzip -q ${filename}.?
queue_log=no

[logfiles]
console => notice,warning,error
messages => notice,warning,error
full => notice,warning,error,verbose(3),dtmf
security => security
